# Generated by Django 5.1.7 on 2025-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('wallet', models.IntegerField(default=0)),
            ],
        ),
    ]
